services:
  postgres:
    image: postgres:alpine
    container_name: Postgres-DB
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    networks:
      - cluster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      dockerfile: Dockerfile
    container_name: Api
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRES_IN=${JWT_ACCESS_EXPIRES_IN}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
    ports:
      - '${PORT}:${PORT}'
    networks:
      - cluster
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migration:run && npm run start:prod"

volumes:
  postgres_data:

networks:
  cluster:
    driver: bridge
